name: Check Issue Link

on:
  push:
    branches:
      - '*'

jobs:
  check_commit_message:
    runs-on: ubuntu-latest

    steps:
      - name: Check Commit Message
        id: check_commit_message
        run: |
          COMMIT_MESSAGE='${{ github.event.head_commit.message }}'
          if [[ $COMMIT_MESSAGE =~ "Merge pull request" || $COMMIT_MESSAGE =~ "Merge branch" || $COMMIT_MESSAGE =~ "Merge remote-tracking branch" || $COMMIT_MESSAGE =~ \(#([0-9]+)\) ]]; then
            echo "Commit message is valid."
          else
            echo "Commit message does not contain an Issue Link."
            exit 1
          fi
